### ISSUE TITLE
Profile Button in inventory screen made larger and list button removed

### ISSUE THREAD

**Issue by IronHide4** [Jindetta/PD2-Custom-Profile-Set#3]
possibly because of the new DLC, or some other change to the game, the profile button on the bottom of the inventory screen has changed.  I hadn't played in a few weeks, and bought the new DLC today and launched the game.  none of my mods had updated, but the button was bigger and the list option for it was gone.  i can only use the arrow keys to go left and right to cycle through my profiles (30 of them).  I disabled this mod and only this mod and it went back to what it used to be. something in this mod and the latest update or DLC are not interacting correctly.

**Comment by IronHide4** [comment]
did some more checking.  the list button is still there, just moved to the side and invisible.

**Comment by powware** [comment]
#5
