### ISSUE TITLE
Mod did not load profiles from json

### ISSUE THREAD

**Issue by powware** [Jindetta/PD2-Custom-Profile-Set#4]
Hey love this mod!
I unfortunately encountered two Issues, the one with the already mentioned multi profile selector button being invisible because of the box size adjustments 
and I ran into the issue that my profiles didn't load from the json anymore. 

I found out, that payday seems to save your added profiles aswell and you check in your load post hooks if profiles and skillsets already exists. They seem to have been loaded so your mod didnt override them anymore. 

Removing [this check](https://github.com/Jindetta/PD2-Custom-Profile-Set/blob/7e75fc83b09dbd5f22b2c013fde2cb085db03c35/Custom%20Profile%20Set/main.lua#L188) and [this check](https://github.com/Jindetta/PD2-Custom-Profile-Set/blob/7e75fc83b09dbd5f22b2c013fde2cb085db03c35/Custom%20Profile%20Set/main.lua#L250) solved the issue.

**Comment by Jindetta** [comment]
Create a pull request and I will update the mod

**Comment by powware** [comment]
#6

**Comment by Jindetta** [comment]
I will update the mod as soon as I can login to ModWorkshop
